2021-07-05 14:48:12 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 14:49:11 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:07:16 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:07:26 ~ MPESAB2C.V2 | ke.co.count.sirib2c.results.ImmediateResponse | 108 | lambda$start$0() | Error database:   - Parameter id was not defined for stored procedure UpdateImmediateResponse. 


2021-07-05 15:08:16 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:11:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:12:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:13:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:14:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:15:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:16:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:17:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:18:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:19:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:20:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:21:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:22:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:23:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


2021-07-05 15:24:54 ~ MPESAB2C.V2 | ke.co.count.sirib2c.datasource.DBConnection | 80 | update_db() | DB Exception  - Invalid object name 'call_back_url_status'.


